//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BasicCapstone
{
    [Serializable]
    public class GraspFeedbackMsg : Message
    {
        public const string k_RosMessageName = "basic_capstone/GraspFeedback";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public float actual_force;
        public string status;

        public GraspFeedbackMsg()
        {
            this.success = false;
            this.actual_force = 0.0f;
            this.status = "";
        }

        public GraspFeedbackMsg(bool success, float actual_force, string status)
        {
            this.success = success;
            this.actual_force = actual_force;
            this.status = status;
        }

        public static GraspFeedbackMsg Deserialize(MessageDeserializer deserializer) => new GraspFeedbackMsg(deserializer);

        private GraspFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.actual_force);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.actual_force);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "GraspFeedbackMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nactual_force: " + actual_force.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
