//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BasicCapstone
{
    [Serializable]
    public class GraspCommandMsg : Message
    {
        public const string k_RosMessageName = "basic_capstone/GraspCommand";
        public override string RosMessageName => k_RosMessageName;

        public float force;
        public string object_type;
        public bool is_fragile;
        public float move_speed;
        public string motion_style;

        public GraspCommandMsg()
        {
            this.force = 0.0f;
            this.object_type = "";
            this.is_fragile = false;
            this.move_speed = 0.0f;
            this.motion_style = "";
        }

        public GraspCommandMsg(float force, string object_type, bool is_fragile, float move_speed, string motion_style)
        {
            this.force = force;
            this.object_type = object_type;
            this.is_fragile = is_fragile;
            this.move_speed = move_speed;
            this.motion_style = motion_style;
        }

        public static GraspCommandMsg Deserialize(MessageDeserializer deserializer) => new GraspCommandMsg(deserializer);

        private GraspCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.force);
            deserializer.Read(out this.object_type);
            deserializer.Read(out this.is_fragile);
            deserializer.Read(out this.move_speed);
            deserializer.Read(out this.motion_style);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force);
            serializer.Write(this.object_type);
            serializer.Write(this.is_fragile);
            serializer.Write(this.move_speed);
            serializer.Write(this.motion_style);
        }

        public override string ToString()
        {
            return "GraspCommandMsg: " +
            "\nforce: " + force.ToString() +
            "\nobject_type: " + object_type.ToString() +
            "\nis_fragile: " + is_fragile.ToString() +
            "\nmove_speed: " + move_speed.ToString() +
            "\nmotion_style: " + motion_style.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
