//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BasicCapstone
{
    [Serializable]
    public class GraspCommandMsg : Message
    {
        public const string k_RosMessageName = "basic_capstone/GraspCommand";
        public override string RosMessageName => k_RosMessageName;

        public float force;
        public string object_type;
        public bool is_fragile;

        public GraspCommandMsg()
        {
            this.force = 0.0f;
            this.object_type = "";
            this.is_fragile = false;
        }

        public GraspCommandMsg(float force, string object_type, bool is_fragile)
        {
            this.force = force;
            this.object_type = object_type;
            this.is_fragile = is_fragile;
        }

        public static GraspCommandMsg Deserialize(MessageDeserializer deserializer) => new GraspCommandMsg(deserializer);

        private GraspCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.force);
            deserializer.Read(out this.object_type);
            deserializer.Read(out this.is_fragile);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force);
            serializer.Write(this.object_type);
            serializer.Write(this.is_fragile);
        }

        public override string ToString()
        {
            return "GraspCommandMsg: " +
            "\nforce: " + force.ToString() +
            "\nobject_type: " + object_type.ToString() +
            "\nis_fragile: " + is_fragile.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
